#define IMG_BACKGROUND                  576
#define IMG_LANGENGLISH					577
#define IMG_LANGTURKISH					578
#define IDI_ICON1						579
#define IDR_MAINTRACK					580

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE		101
#define _APS_NEXT_COMMAND_VALUE			40001
#define _APS_NEXT_CONTROL_VALUE			1001
#define _APS_NEXT_SYMED_VALUE			101
#endif
#endif
